FROM python:3.11-slim
WORKDIR /app

# streamlit deps
RUN pip install --upgrade pip && pip install streamlit==1.37.0 requests

COPY movies_v2/ui /app/ui

EXPOSE 8501
ENV UI_API_BASE=http://api:8000

CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--browser.gatherUsageStats=false"]
